// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetRentalCore;

namespace PetRentalCore.Migrations
{
    [DbContext(typeof(PetRentalContext))]
    partial class PetRentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PetRentalCore.Model.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("OneDayRentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PetTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetTypeId");

                    b.HasIndex("SizeId");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessoryName = "Kurtka Randig",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 1,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessoryName = "Kurtka Randig",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AccessoryName = "Kurtka Randig",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 1,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 4,
                            AccessoryName = "Kurtka Randig",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 1,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 5,
                            AccessoryName = "Kurtka Randig",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 1,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 6,
                            AccessoryName = "Kurtka Dotted",
                            OneDayRentalPrice = 9.00m,
                            PetTypeId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 7,
                            AccessoryName = "Kurtka Dotted",
                            OneDayRentalPrice = 9.00m,
                            PetTypeId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 8,
                            AccessoryName = "Kurtka Dotted",
                            OneDayRentalPrice = 9.00m,
                            PetTypeId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccessoryName = "Kurtka Dotted",
                            OneDayRentalPrice = 9.00m,
                            PetTypeId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 10,
                            AccessoryName = "Kurtka Dotted",
                            OneDayRentalPrice = 9.00m,
                            PetTypeId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 11,
                            AccessoryName = "Szelki Stripped",
                            OneDayRentalPrice = 3.00m,
                            PetTypeId = 1,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 12,
                            AccessoryName = "Szelki Stripped",
                            OneDayRentalPrice = 3.00m,
                            PetTypeId = 1,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 13,
                            AccessoryName = "Szelki Stripped",
                            OneDayRentalPrice = 3.00m,
                            PetTypeId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 14,
                            AccessoryName = "Szelki Stripped",
                            OneDayRentalPrice = 3.00m,
                            PetTypeId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 15,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 16,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 17,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 18,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 19,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 20,
                            AccessoryName = "Szelki Malutkie",
                            OneDayRentalPrice = 5.00m,
                            PetTypeId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 21,
                            AccessoryName = "Sweterek w Kwaiatki",
                            OneDayRentalPrice = 4.00m,
                            PetTypeId = 6,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 22,
                            AccessoryName = "Sweterek w Kwaiatki",
                            OneDayRentalPrice = 4.00m,
                            PetTypeId = 6,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 23,
                            AccessoryName = "Sweterek w Kwaiatki",
                            OneDayRentalPrice = 4.00m,
                            PetTypeId = 6,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 24,
                            AccessoryName = "Sweterek w Kwaiatki",
                            OneDayRentalPrice = 4.00m,
                            PetTypeId = 6,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 25,
                            AccessoryName = "Kurtka smiley",
                            OneDayRentalPrice = 20.00m,
                            PetTypeId = 7,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 26,
                            AccessoryName = "Kurtka smiley",
                            OneDayRentalPrice = 20.00m,
                            PetTypeId = 7,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 27,
                            AccessoryName = "Kurtka smiley",
                            OneDayRentalPrice = 20.00m,
                            PetTypeId = 7,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 28,
                            AccessoryName = "Kurtka smiley",
                            OneDayRentalPrice = 20.00m,
                            PetTypeId = 7,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 29,
                            AccessoryName = "Kurtka smiley",
                            OneDayRentalPrice = 20.00m,
                            PetTypeId = 7,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 30,
                            AccessoryName = "Kurtka grey",
                            OneDayRentalPrice = 17.00m,
                            PetTypeId = 7,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 31,
                            AccessoryName = "Kurtka grey",
                            OneDayRentalPrice = 17.00m,
                            PetTypeId = 7,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 32,
                            AccessoryName = "Kurtka grey",
                            OneDayRentalPrice = 17.00m,
                            PetTypeId = 7,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 33,
                            AccessoryName = "Szelki piggy",
                            OneDayRentalPrice = 13.00m,
                            PetTypeId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 34,
                            AccessoryName = "Szelki piggy",
                            OneDayRentalPrice = 13.00m,
                            PetTypeId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 35,
                            AccessoryName = "Kurtka warmy",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 36,
                            AccessoryName = "Kurtka warmy",
                            OneDayRentalPrice = 10.00m,
                            PetTypeId = 8,
                            SizeId = 5
                        });
                });

            modelBuilder.Entity("PetRentalCore.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1995, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Katarzyna",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 257, DateTimeKind.Local).AddTicks(2066),
                            Surname = "Jablonska"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1996, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agnieszka",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 260, DateTimeKind.Local).AddTicks(9679),
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Agnieszka",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 260, DateTimeKind.Local).AddTicks(9806),
                            Surname = "Babacka"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1986, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mateusz",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 260, DateTimeKind.Local).AddTicks(9839),
                            Surname = "Dadacki"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1999, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marcin",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 260, DateTimeKind.Local).AddTicks(9867),
                            Surname = "Abacki"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1978, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ewa",
                            RegistrationDate = new DateTime(2021, 2, 15, 19, 15, 59, 260, DateTimeKind.Local).AddTicks(9915),
                            Surname = "Jakas"
                        });
                });

            modelBuilder.Entity("PetRentalCore.Model.PetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PetTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PetTypeName = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            PetTypeName = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            PetTypeName = "Parrot"
                        },
                        new
                        {
                            Id = 4,
                            PetTypeName = "Mouse"
                        },
                        new
                        {
                            Id = 5,
                            PetTypeName = "Rat"
                        },
                        new
                        {
                            Id = 6,
                            PetTypeName = "Hamster"
                        },
                        new
                        {
                            Id = 7,
                            PetTypeName = "Horse"
                        },
                        new
                        {
                            Id = 8,
                            PetTypeName = "Pig"
                        });
                });

            modelBuilder.Entity("PetRentalCore.Model.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccessoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("PetRentalCore.Model.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SizeName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SizeName = 0
                        },
                        new
                        {
                            Id = 2,
                            SizeName = 1
                        },
                        new
                        {
                            Id = 3,
                            SizeName = 2
                        },
                        new
                        {
                            Id = 4,
                            SizeName = 3
                        },
                        new
                        {
                            Id = 5,
                            SizeName = 4
                        });
                });

            modelBuilder.Entity("PetRentalCore.Model.Accessory", b =>
                {
                    b.HasOne("PetRentalCore.Model.PetType", "PetType")
                        .WithMany("Accessories")
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetRentalCore.Model.Size", "Size")
                        .WithMany("Accessories")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetType");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("PetRentalCore.Model.Rental", b =>
                {
                    b.HasOne("PetRentalCore.Model.Accessory", "Accessory")
                        .WithMany("Rentals")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetRentalCore.Model.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PetRentalCore.Model.Accessory", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("PetRentalCore.Model.Client", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("PetRentalCore.Model.PetType", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("PetRentalCore.Model.Size", b =>
                {
                    b.Navigation("Accessories");
                });
#pragma warning restore 612, 618
        }
    }
}
